package com.ivan.jhs.persistence;
// Generated 30-ene-2016 19:28:20 by Hibernate Tools 4.3.1



/**
 * Login generated by hbm2java
 */
public class Login  implements java.io.Serializable {


     private String usuario;
     private String password;
     private String nombre;
     private int edad;

    public Login() {
    }

    public Login(String usuario, String password, String nombre, int edad) {
       this.usuario = usuario;
       this.password = password;
       this.nombre = nombre;
       this.edad = edad;
    }
   
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public int getEdad() {
        return this.edad;
    }
    
    public void setEdad(int edad) {
        this.edad = edad;
    }




}


