package usuarios.bean;
// Generated 31-ene-2016 19:47:22 by Hibernate Tools 4.3.1

import com.opensymphony.xwork2.ActionContext;
import com.opensymphony.xwork2.ActionSupport;
import java.util.Map;
import usuarios.dao.ContactosDAO;




/**
 * Login generated by hbm2java
 */
public class Login extends ActionSupport implements java.io.Serializable {


     private String usuario;
     private String password;
     private String nombre;
     private int edad;
     private String mensaje;
     private Map session;

    public Login() {
    }

    public Login(String usuario, String password, String nombre, int edad) {
       this.usuario = usuario;
       this.password = password;
       this.nombre = nombre;
       this.edad = edad;
    }
    
     @Override
    public String execute(){
        
        ContactosDAO conta = new ContactosDAO();
         
        Login lo = conta.logIn(nombre,password);
        if(lo != null){
            session = ActionContext.getContext().getSession();
            session.put("Access", true);
            session.put("Usuario", lo.getNombre());
            setMensaje("Bienvenido"+lo.getNombre());
            return SUCCESS;
        }else{
            setMensaje("Usuario y Password Incorrectos");
            return ERROR;
        }
        
    }
   
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public int getEdad() {
        return this.edad;
    }
    
    public void setEdad(int edad) {
        this.edad = edad;
    }

    /**
     * @return the mensaje
     */
    public String getMensaje() {
        return mensaje;
    }

    /**
     * @param mensaje the mensaje to set
     */
    public void setMensaje(String mensaje) {
        this.mensaje = mensaje;
    }

    /**
     * @return the session
     */
    public Map getSession() {
        return session;
    }

    /**
     * @param session the session to set
     */
    public void setSession(Map session) {
        this.session = session;
    }




}


